### ISSUE TITLE
App crashes on opening settings dialog

### ISSUE THREAD

**Issue by arnep-de** [alterakey/effy#9]
When I open the "settings" dialog the app crashes. Here is the log data from `adb logcat`. My system is Android 6.0.1/CyanogenMod 13.0

`02-14 21:06:45.262   572  2895 I ActivityManager: START u0 {cmp=com.gmail.altakey.effy/.ConfigActivity} from uid 10135 on display 0
02-14 21:06:45.364 13832 13832 D AndroidRuntime: Shutting down VM
02-14 21:06:45.366 13832 13832 E AndroidRuntime: FATAL EXCEPTION: main
02-14 21:06:45.366 13832 13832 E AndroidRuntime: Process: com.gmail.altakey.effy, PID: 13832
02-14 21:06:45.366 13832 13832 E AndroidRuntime: Theme: themes:{}
02-14 21:06:45.366 13832 13832 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.gmail.altakey.effy/com.gmail.altakey.effy.ConfigActivity}: java.util.FormatFlagsConversionMismatchException: %o does not support '('
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3137)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: Caused by: java.util.FormatFlagsConversionMismatchException: %o does not support '('
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at java.util.Formatter$FormatToken.checkFlags(Formatter.java:1361)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at java.util.Formatter.transform(Formatter.java:1442)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at java.util.Formatter.doFormat(Formatter.java:1081)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:1042)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:1011)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at java.lang.String.format(String.java:1554)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at java.lang.String.format(String.java:1528)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at android.preference.ListPreference.getSummary(ListPreference.java:169)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at com.gmail.altakey.effy.ConfigActivity.setSummary(ConfigActivity.java:79)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at com.gmail.altakey.effy.ConfigActivity.updateSummary(ConfigActivity.java:69)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at com.gmail.altakey.effy.ConfigActivity.onResume(ConfigActivity.java:48)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6327)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
02-14 21:06:45.366 13832 13832 E AndroidRuntime: 	... 10 more
02-14 21:06:45.368   572   590 W ActivityManager:   Force finishing activity com.gmail.altakey.effy/.ConfigActivity
02-14 21:06:45.371   572   590 W ActivityManager:   Force finishing activity com.gmail.altakey.effy/.DrawActivity
`

**Comment by sneetsher** [comment]
Same here with Android 4.0.4 / Toshiba Thrive AT100.

Here is the catlog, 
[alogcat.2017-06-12-04-51-10+0100.txt](https://github.com/taky/effy/files/1067067/alogcat.2017-06-12-04-51-10.0100.txt)
